### ISSUE TITLE
Complex bezier curve sequences use the wrong control point

### ISSUE THREAD

**Issue by jameswilson** [mathieudutour/svg-path-visualizer#15]
This project is awesome!  Thank you, thank you, thank you for your time invested here.  I think I may have found a bug, but I'm just an SVG enthusiast, not a pro. 

Given the following valid SVG path code with a complex sequence of bezier curves that use multiple `T`s:

[`M0 10L 0 4Q 16 8 32 3T 64 4T 96 4T 128 5T 160 4L 160 10 Z`](https://svg-path-visualizer.netlify.app/#M0%2010L%200%204Q%2016%208%2032%203T%2064%204T%2096%204T%20128%205T%20160%204L%20160%2010%20Z)

```svg
<svg viewBox="0 0 160 10">
  <path d="
    M 0,10
    L 0,4
    Q 16,8 32,3
    T 64,4
    T 96,4
    T 128,5
    T 160,4
    L 160,10
    Z"/>
</svg>
```

the path visualizer appears to use the wrong control point starting from the second `T` after the start of the `Q` `T` sequence.

**What the browsers render:**

<img width="899" alt="Screen Shot 2021-07-22 at 8 32 25 PM" src="https://user-images.githubusercontent.com/243532/126727984-4fd20990-6f09-450d-b81c-2c18f0c447d2.png">

**What the visualizer renders:**

<img width="898" alt="Screen Shot 2021-07-22 at 8 31 13 PM" src="https://user-images.githubusercontent.com/243532/126727993-7f86e73b-a4ee-40b8-88cc-5192c8554d9a.png">

**Comment by mathieudutour** [comment]
That def looks like a bug 😄

**Comment by mathieudutour** [comment]
should be fixed now
