### ISSUE TITLE
Poor representation of a particular svg

### ISSUE THREAD

**Issue by ssupinsky** [mathieudutour/svg-path-visualizer#2]
Hi. Loved your tool, awesome stuff!

I just found out though that his particular svg is not drawn right:
https://svg-path-visualizer.netlify.app/#M30.148%205.588c-2.934-3.42-7.288-5.588-12.148-5.588-8.837%200-16%207.163-16%2016s7.163%2016%2016%2016c4.86%200%209.213-2.167%2012.148-5.588l-10.148-10.412%2010.148-10.412zM22%203.769c1.232%200%202.231%200.999%202.231%202.231s-0.999%202.231-2.231%202.231-2.231-0.999-2.231-2.231c0-1.232%200.999-2.231%202.231-2.231z
Here it is in the wild:
https://codepen.io/team/css-tricks/pen/yebOYp

**Comment by mathieudutour** [comment]
That was a sad pacman!
Should be fixed now, thanks for the report
