### ISSUE TITLE
Does not render correctly for some Beizer curve

### ISSUE THREAD

**Issue by graphemecluster** [mathieudutour/svg-path-visualizer#5]
This is the path of the character `m` in a certain font:
```
M1627 1798v-633q0 -183 -25.5 -244.5t-78 -90t-132.5 -28.5q-137 0 -323 151q6 52 6 133v712h-176v-633q0 -188 -25.5 -247.5t-77 -87.5t-130.5 -28q-143 0 -319 146v850h-176v-1130h176v136q201 -168 380 -168q231 0 312 185q218 -185 414 -185q351 0 351 426v736h-176z
```
And it looks like this:
![svg](https://user-images.githubusercontent.com/53967830/91611237-661cd100-e9ad-11ea-94fa-35edfe993082.png)

Control points shown in FontForge:
![FontForge](https://user-images.githubusercontent.com/53967830/91611158-3c63aa00-e9ad-11ea-850e-2fdffe5c5ca3.png)

This is what the visualizer rendering:
[https://svg-path-visualizer.netlify.app/#M1627%201798v-633q0%20-183%20-25.5…](https://svg-path-visualizer.netlify.app/#M1627%201798v-633q0%20-183%20-25.5%20-244.5t-78%20-90t-132.5%20-28.5q-137%200%20-323%20151q6%2052%206%20133v712h-176v-633q0%20-188%20-25.5%20-247.5t-77%20-87.5t-130.5%20-28q-143%200%20-319%20146v850h-176v-1130h176v136q201%20-168%20380%20-168q231%200%20312%20185q218%20-185%20414%20-185q351%200%20351%20426v736h-176z)

A more complicated example: the Chinese character (Kanji) `恋`:
```
M372 1185l-67 -102q218 -96 330 -240.5t115 -411.5h-664v-119h852v-204h163v204h838v119h-604v539q0 69 -54.5 113t-135.5 44h-203l-18 -136h163q87 0 87 -73v-487h-272q-11 344 -154 502t-376 252zM172 1010l-99 -88q230 -175 337 -392l138 46q-34 86 -147 217t-229 217
zM1853 1085q-92 -70 -212.5 -224.5t-171.5 -262.5l140 -48q113 219 359 441zM1032 1553q-134 -226 -184 -292l130 -61q86 110 194 284zM552 1250h165v420q0 63 49.5 76.5t273.5 13.5q93 0 166 -6.5t95.5 -16t39 -30.5t23 -53.5t13.5 -200.5l144 17v248q0 70 -49 114
t-219.5 50t-225.5 6q-70 0 -145 -3t-155 -9t-114 -31t-47.5 -58t-13.5 -77v-460zM1851 1789q-105 -208 -276 -466l138 -69q60 81 154 234t132 232zM205 1835l-142 -60q119 -182 184 -437l146 27q-42 212 -188 470z
```

And it should look like this:
![svg](https://user-images.githubusercontent.com/53967830/91611465-ee02db00-e9ad-11ea-9455-134b3afcbb0f.png)

Control points shown in FontForge (may be different from the svg file):
![FontForge](https://user-images.githubusercontent.com/53967830/91611550-1ee31000-e9ae-11ea-84c5-da91c9fc1f04.png)

And this is what the visualizer rendering:
[https://svg-path-visualizer.netlify.app/#M372%201185l-67%20-102q218%20-96…](https://svg-path-visualizer.netlify.app/#M372%201185l-67%20-102q218%20-96%20330%20-240.5t115%20-411.5h-664v-119h852v-204h163v204h838v119h-604v539q0%2069%20-54.5%20113t-135.5%2044h-203l-18%20-136h163q87%200%2087%20-73v-487h-272q-11%20344%20-154%20502t-376%20252zM172%201010l-99%20-88q230%20-175%20337%20-392l138%2046q-34%2086%20-147%20217t-229%20217%20zM1853%201085q-92%20-70%20-212.5%20-224.5t-171.5%20-262.5l140%20-48q113%20219%20359%20441zM1032%201553q-134%20-226%20-184%20-292l130%20-61q86%20110%20194%20284zM552%201250h165v420q0%2063%2049.5%2076.5t273.5%2013.5q93%200%20166%20-6.5t95.5%20-16t39%20-30.5t23%20-53.5t13.5%20-200.5l144%2017v248q0%2070%20-49%20114%20t-219.5%2050t-225.5%206q-70%200%20-145%20-3t-155%20-9t-114%20-31t-47.5%20-58t-13.5%20-77v-460zM1851%201789q-105%20-208%20-276%20-466l138%20-69q60%2081%20154%20234t132%20232zM205%201835l-142%20-60q119%20-182%20184%20-437l146%2027q-42%20212%20-188%20470z)

I hope you can fix this and thank you for reading.

**Comment by mathieudutour** [comment]
Thanks for the nice report! Should be fixed now (https://github.com/mathieudutour/svg-path-visualizer/commit/bb775d6b26271d865aca26fe0aad3c57ff39a95f)

**Comment by graphemecluster** [comment]
Thank you for the fast response!
